name: Docker Build and Trivy Scan

on:
  workflow_call:
    inputs:
      DOCKER_PATH_CONTEXT:
        required: true
        type: string
      DOCKER_BUILD_DOCKERFILE:
        required: true
        type: string
      DOCKER_TAGS:
        required: true
        type: string
      DOCKER_LOAD_BOOL:
        required: false
        type: boolean
        default: false

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build (and maybe push) Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{  inputs.DOCKER_PATH_CONTEXT }}
          file: ${{  inputs.DOCKER_BUILD_DOCKERFILE}}
          load: ${{ inputs.DOCKER_LOAD_BOOL }}
          push: ${{ github.event_name == 'workflow_call' }}
          tags: ${{  inputs.DOCKER_TAGS }}
      - name: Run Trivy vulnerability scanner (remote)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: docker.io/${{ inputs.DOCKER_TAGS }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
